export enum BodyStyle {
  SEDAN = 'SEDAN',
  KOMBI = 'KOMBI',
  HATCHBACK = 'HATCHBACK',
  COUPE = 'COUPE',
  CABRIOLET = 'CABRIOLET',
  MICRO = 'MICRO',
  VAN = 'VAN',
  SUV = 'SUV',
  PICKUP = 'PICKUP',
  SUPER_CAR = 'SUPER_CAR',
}
